name = "ancika"
compatibility_date = "2023-12-01"

main = "src/index.ts"
minify = true

# [vars]
# ENDPOINT_NAME = ""
# UMAMI_URL = ""

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"
